# Generated by Django 4.2.16 on 2024-12-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, unique=True, verbose_name='Palavra')),
            ],
            options={
                'verbose_name': 'Palavra',
                'verbose_name_plural': 'Palavras',
                'ordering': ['texto'],
            },
        ),
    ]
