# Generated by Django 5.1.2 on 2024-12-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('attempts', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termooo.word')),
            ],
        ),
    ]
