# Generated by Django 4.2.16 on 2024-12-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termooo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='texto',
            field=models.CharField(max_length=5, unique=True, verbose_name='Palavra'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('attempts', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termooo.palavra')),
            ],
        ),
    ]
